version: '3.8'

services:

  postgres-segments:
    image: postgres:17
    container_name: analyticsPersist
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: userSegmentsDB
    ports:
      - "5431:5432"
    volumes:
      - postgres_userSegments:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_userSegments:

networks:
  app-network:
    driver: bridge
    name: spark-network