version: '3.8'

services:

  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: userSegmentsDB
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres-segments
      #Kafka
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka_producer:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: analytics-service-group
      SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: earliest
      SPRING_KAFKA_CONSUMER_ENABLE_AUTO_COMMIT: "false"
      #Security
      SIGNATURE_KEY: P25epMoWb4VgLPm2V20X6z8qJWPbZmEpV97tf4PbH4PHqgtZNR6E0xXONoOEDC7w
    depends_on:
      - postgres-segments
    networks:
      - app-network

  postgres-segments:
    image: postgres:17
    container_name: analyticsPersist
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: userSegmentsDB
    ports:
      - "5431:5432"
    volumes:
      - postgres_userSegments:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_userSegments:

networks:
  app-network:
    driver: bridge
    name: spark-network