CREATE TABLE IF NOT EXISTS invite_tokens (
    token_id SERIAL PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(50) DEFAULT 'ANALYST',
    used BOOLEAN DEFAULT FALSE,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);